version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12.3  # Specify the Python version
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install virtualenv

  pre_build:
    commands:
      - echo Setting up virtual environment...
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r src/requirements.txt

  build:
    commands:
      - echo Collecting static files...
      - source venv/bin/activate
      - python src/manage.py collectstatic --noinput

      - echo Running tests...
      - python src/manage.py test



