version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12.3  # Specify the Python version
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install virtualenv

  pre_build:
    commands:
      - echo Setting up virtual environment...
      - cd src  # Navigate to the src direct  ory
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
      - pwd
      - ls
  build:
    commands:
      - echo Collecting static files...
      - cd src  # Navigate to the src directory
      - source venv/bin/activate
      - python manage.py collectstatic --noinput
      - echo Running tests...
      - python manage.py test

  post_build:
    commands:
      - echo Zipping the source code...
      - cd src  # Navigate to the src directory
      - zip -r ../deployment_bundle.zip . -x "*.git*" "*.DS_Store"

artifacts:
  files:
    - '**/*'