version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12.3  # Specify the Python version
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install virtualenv

  pre_build:
    commands:
      - echo Setting up virtual environment...
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r src/requirements.txt

  build:
    commands:
      - echo Collecting static files...
      - source venv/bin/activate
      - python src/manage.py collectstatic --noinput
      - echo Syncing the static files...
      - aws s3 sync src/static/ s3://x23377852-maximum.s3.amazonaws.com/static/ --acl public-read
      - echo Running tests...
      - python src/manage.py test

  post_build:
    commands:
      - echo Zipping the source code...
      - ls
      - zip -r deployment_bundle.zip . -x "*.git*" "*.DS_Store"


artifacts:
  files:
    - deployment_bundle.zip


eb_codebuild_settings:
  artifact_name: deployment_bundle.zip
  deployment_package: true