version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Specify the Python version
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install virtualenv

  pre_build:
    commands:
      - echo Setting up virtual environment...
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt

  build:
    commands:
      - echo Collecting static files...
      - python manage.py collectstatic --noinput
      - echo Running tests...
      - python manage.py test

  post_build:
    commands:
      - echo Zipping the source code...
      - zip -r deployment-bundle.zip . -x "*.git*" "*.DS_Store"

artifacts:
  files:
    - deployment-bundle.zip
  discard-paths: yes