version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/maximum
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
    - location: scripts/migrate_database.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300