# Generated by Django 5.1.6 on 2025-03-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing_brand_listing_color_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='engine',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='listing',
            name='model',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='listing',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=24),
        ),
        migrations.AlterField(
            model_name='listing',
            name='vin',
            field=models.CharField(max_length=17),
        ),
    ]
